require: rubocop-rails

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Include:
    - 'app/views/api/**/*.rabl'
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'release-gem'
    - 'extra/discover-host'
    - 'test/**/*'

Layout:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Naming:
  Enabled: false
